### ISSUE TITLE
error compile webapp

### ISSUE THREAD

**Issue by Olivier4477** [rshtishi/payroll#2] opened 2020-08-06 17:43 UTC
Compiling ngx-bootstrap/typeahead : es2015 as esm2015

chunk {main} main.js, main.js.map (main) 676 bytes [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 731 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 2.6 MB [initial] [rendered]
Date: 2020-08-06T17:10:38.296Z - Hash: 94ca68148af00f4f4db0 - Time: 13733ms

ERROR in src/app/layout/dashboard/dashboard/dashboard.component.ts:2:35 - error TS2307: Cannot find module '../../../shared/service/department.service' or its corresponding type declarations.

2 import { DepartmentService } from '../../../shared/service/department.service';
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@0.0.0 build: `ng build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Damien\AppData\Roaming\npm-cache\_logs\2020-08-06T17_10_38_431Z-debug.log
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:804)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:751)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:313)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)

Log npm:
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle test@0.0.0~prebuild: test@0.0.0
6 info lifecycle test@0.0.0~build: test@0.0.0
7 verbose lifecycle test@0.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle test@0.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Damien\OneDrive - Ma Formation en Ligne\Spring\projet payroll\payroll\webapp\node_modules\.bin;C:\Users\Damien\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Damien\bin;C:\opt\Zulu 1.14.27.1\zulu14.27.1-ca-jdk14-win_x64\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files (x86)\Common Files\Acronis\VirtualFile;C:\Program Files (x86)\Common Files\Acronis\VirtualFile64;C:\Program Files (x86)\Common Files\Acronis\SnapAPI;C:\Program Files\Crucial\Crucial Storage Executive;C:\ProgramData\chocolatey\bin;C:\opt\apache-maven-3.6.3\bin;C:\Program Files\nodejs;C:\Program Files (x86)\AOMEI\AOMEI Backupper 5.7.0;C:\Program Files\Git\cmd;C:\tools\php74;C:\ProgramData\ComposerSetup\bin;C:\Program Files\MySQL\MySQL Shell 8.0\bin;C:\Users\Damien\AppData\Local\Microsoft\WindowsApps;C:\Users\Damien\AppData\Roaming\Dashlane\6.1950.0.28527\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components;C:\Users\Damien\AppData\Roaming\Dashlane\6.1950.0.28527\ucrt;C:\Users\Damien\AppData\Roaming\Dashlane\6.1950.0.28527\bin\Qt;C:\Users\Damien\AppData\Roaming\Dashlane\6.1950.0.28527\bin\Ssl;C:\Users\Damien\AppData\Local\Programs\Microsoft VS Code Insiders\bin;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3\bin;C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.2\bin;C:\Users\Damien\AppData\Roaming\npm;C:\Users\Damien\AppData\Local\Microsoft\WindowsApps\Local\Programs\Python\Python38\Scripts;C:\Users\Damien\AppData\Roaming\Composer\vendor\bin;C:\Program Files (x86)\EaseUS\Todo Backup\bin\x64;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle test@0.0.0~build: CWD: C:\Users\Damien\OneDrive - Ma Formation en Ligne\Spring\projet payroll\payroll\webapp
10 silly lifecycle test@0.0.0~build: Args: [ '/d /s /c', 'ng build' ]
11 silly lifecycle test@0.0.0~build: Returned: code: 1  signal: null
12 info lifecycle test@0.0.0~build: Failed to exec build script
13 verbose stack Error: test@0.0.0 build: `ng build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid test@0.0.0
15 verbose cwd C:\Users\Damien\OneDrive - Ma Formation en Ligne\Spring\projet payroll\payroll\webapp
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error test@0.0.0 build: `ng build`
22 error Exit status 1
23 error Failed at the test@0.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by rshtishi** [comment] 2020-08-06 17:54
Hi Olivier4477,

I am developing a user interface as a sub module of the payroll project. 
To  bypass this error you can :
1-  move the master branch to point at commit: 8366c68ecc7488c4937c1aaa1f4951af69eca849 (if you are not interested to have an angular app to test the microservices )

2- install the following:
Node JS version:  v13.9.0 (you can use nvm for working with multiple version of node js)
npm version: 6.13.7
 Angular CLI: 10.0.4

**Comment by Olivier4477** [comment] 2020-08-06 18:00
Ok sorry I don't have the latest version of npm and I just saw js-cli, sorry I test and I close issue if it's good,

thank you

**Comment by Olivier4477** [comment] 2020-08-06 19:24
I have the following versions:
angular-cli 10.0.5
nodejs v14.7.0
npm v6.17.7
and i still have the same problem

**Comment by rshtishi** [comment] 2020-08-06 19:36
Execute the command below:
```ng add @progress/kendo-angular-charts```

I am using kendo UI charts, in dashboard, maybe this is problem.

**Comment by Olivier4477** [comment] 2020-08-06 20:53
/payroll/webapp (master)
$ ng add @progress/kendo-angular-charts
Installing packages for tooling via npm.
Installed packages for tooling via npm.
            @progress/kendo-theme-default already installed, skipping styles registration.
UPDATE package.json (1721 bytes)
- Installing packages...
ÔêÜ Packages installed successfully.


Sorry, i have the same problem

**Comment by rshtishi** [comment] 2020-08-07 07:03
You don't need to have Redis or Kafka in order to build the project successfully.
Can you please provide the logs in the file:
 C:\Users\Damien\AppData\Roaming\npm-cache_logs\2020-08-06T17_10_38_431Z-debug.log.

I will take a look when I have time.

**Comment by Olivier4477** [comment] 2020-08-07 07:06
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle test@0.0.0~prebuild: test@0.0.0
6 info lifecycle test@0.0.0~build: test@0.0.0
7 verbose lifecycle test@0.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle test@0.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Damien\OneDrive - Ma Formation en Ligne\Spring\projet payroll\payroll\webapp\node_modules\.bin;C:\Users\Damien\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Damien\bin;C:\opt\Zulu 1.14.27.1\zulu14.27.1-ca-jdk14-win_x64\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files (x86)\Common Files\Acronis\VirtualFile;C:\Program Files (x86)\Common Files\Acronis\VirtualFile64;C:\Program Files (x86)\Common Files\Acronis\SnapAPI;C:\Program Files\Crucial\Crucial Storage Executive;C:\ProgramData\chocolatey\bin;C:\opt\apache-maven-3.6.3\bin;C:\Program Files\nodejs;C:\Program Files (x86)\AOMEI\AOMEI Backupper 5.7.0;C:\Program Files\Git\cmd;C:\tools\php74;C:\ProgramData\ComposerSetup\bin;C:\Program Files\MySQL\MySQL Shell 8.0\bin;C:\Users\Damien\AppData\Local\Microsoft\WindowsApps;C:\Users\Damien\AppData\Roaming\Dashlane\6.1950.0.28527\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components;C:\Users\Damien\AppData\Roaming\Dashlane\6.1950.0.28527\ucrt;C:\Users\Damien\AppData\Roaming\Dashlane\6.1950.0.28527\bin\Qt;C:\Users\Damien\AppData\Roaming\Dashlane\6.1950.0.28527\bin\Ssl;C:\Users\Damien\AppData\Local\Programs\Microsoft VS Code Insiders\bin;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3\bin;C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.2\bin;C:\Users\Damien\AppData\Roaming\npm;C:\Users\Damien\AppData\Local\Microsoft\WindowsApps\Local\Programs\Python\Python38\Scripts;C:\Users\Damien\AppData\Roaming\Composer\vendor\bin;C:\Program Files (x86)\EaseUS\Todo Backup\bin\x64;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle test@0.0.0~build: CWD: C:\Users\Damien\OneDrive - Ma Formation en Ligne\Spring\projet payroll\payroll\webapp
10 silly lifecycle test@0.0.0~build: Args: [ '/d /s /c', 'ng build' ]
11 silly lifecycle test@0.0.0~build: Returned: code: 1  signal: null
12 info lifecycle test@0.0.0~build: Failed to exec build script
13 verbose stack Error: test@0.0.0 build: `ng build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid test@0.0.0
15 verbose cwd C:\Users\Damien\OneDrive - Ma Formation en Ligne\Spring\projet payroll\payroll\webapp
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error test@0.0.0 build: `ng build`
22 error Exit status 1
23 error Failed at the test@0.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by rshtishi** [comment] 2020-08-07 07:18
It seems there is no problem with npm.  Check the solution below:

https://stackoverflow.com/questions/40419682/angularjs-typescript-error-ts2307-cannot-find-module-angular

**Comment by Olivier4477** [comment] 2020-08-09 11:39
ERROR in src/app/layout/dashboard/dashboard/dashboard.component.ts:2:35 - error TS2307: Cannot find module '../../../shared/service/department.service' or its corresponding type declarations.

It's a shame because I still have the same problem, even after doing several things, I can't run the webapp

**Comment by rshtishi** [comment] 2020-08-09 14:26
Currently, I am still working to finish the web app. I added some fixes, you can try to get the latest version and run another build.  When I finish the development, and the problem still persists, I will try to reproduce in another virtual machine and see if shows the same errors.

**Comment by rshtishi** [comment] 2020-08-12 19:01
I finished the implementation of the web app. Please download the latest version of payroll and check if you are able to run a successful build. Before running the build check if you have installed:
Node JS version: v13.9.0 
npm version: 6.13.7
Angular CLI: 10.0.4
You may have installed the new version of nodejs and npm, nevertheless, you should check if it is running with the new version or somehow is using the old ones.

**Comment by Olivier4477** [comment] 2020-08-14 08:19
ok I look at this as soon as possible (as soon as I have the time)

**Comment by Olivier4477** [comment] 2020-08-16 15:44
Ok it's good, it completes all the compilations correctly.
On the other hand (I haven't done angular yet), I don't understand how to access index.html with https: // localhost: 5555

Small detail, if I git clone and mvn install, there is a problem with the link with the logkback, because the folder must be created before.

**Comment by rshtishi** [comment] 2020-08-17 15:20
Prerequisite before starting angular: 
- run success build of the entire payroll project
- start all services of payroll

Start angular by running ```npm start``` in webapp submodule.
After that, you can access it in the URL : ```localhost:4200``` .

I am closing this issue since you were able to successfully build the project.

**Closed by rshtishi** 2020-08-17 15:20 UTC

**Comment by Olivier4477** [comment] 2020-08-30 12:55
ok everything works! thank you!
the url 4200 only points to dashboard? there is no index?
and i can't identify with http://localhost:8901/oauth/token

**Comment by rshtishi** [comment] 2020-08-30 13:43
The first time you access ```localhost:4200```, it will redirect you to the login page ```localhost:4200/login```. After a successful login, you will be redirected to the dashboard page.  To authenticate, we don't use directly the URL  ```http://localhost:8901/oauth/token```, but instead we use the gateway server to access the oauth2 server. Remember that only the gateway server is accessible from the client. You are going to use the login page for authentication and behind the scenes the login page access the endpoint : ```https://localhost:5555/payroll/oauth2/oauth/token``` to perform the authentication.
